### PR TITLE
Initial version of .travis.yml

### PR DESCRIPTION
**Pull request by rihards**
Just a simple travis config that will (currently) run `npm run lint`.

For this to work, need to login and enable the repository at https://travis-ci.org/

But you can already check it working in my fork:
https://travis-ci.org/rihards/Coonti

edit: forgot to mention that this is for issue #9

### CODE REVIEW

**Comment by rihards** [comment]
Also added four eslint fixes that were spotted by travis. This should make the build pass now.

**Comment by rihards** [comment]
Could also add the build status image to the repository:
https://docs.travis-ci.com/user/status-images/

**Comment by jannekalliola** [comment]
Thank you for this! Would you be also so kind to make relevant changes to readme.md to instruct others to use the solution?

Also, can issue #9 be closed based on this?

**Comment by rihards** [comment]
#9 can be closed, and I don't think there's need for readme update, except for maybe mentioning `npm run lint` because travis takes care of everything else automatically. Basically any next time that there is a pull request in this repo, Travis will report in that pull request whether all tests / scripts passed.

**Pull request merged**
